proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apl.url'))
]

apl/models.py
from django.db import models


class Application(models.Model):
    SEMESTER_CHOICES = [
        ('не срочно', 'Не срочно'),
        ('срочно', 'Срочно'),
        ('очень срочно', 'Очень срочно'), ]

    title = models.CharField(max_length=225)
    text = models.TextField()
    date_create = models.DateField(auto_now_add=True)
    urgency = models.CharField(
        max_length=20,
        choices=SEMESTER_CHOICES,
        default='не срочно'
    )

    def __str__(self):
        return f'{self.title}'

class Files(models.Model):

    file = models.FileField(upload_to='application', blank=True, null=True, verbose_name='Файл')
    application = models.ForeignKey(Application, blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Файлы"
        verbose_name_plural = "Файлы"

    def __str__(self):
        return self.file.name

apl/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import reverse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView

from apl.form import ApplicationForm
from apl.models import Application, Files


class ApplicationListView(ListView):
    model = Application
    form_class = ApplicationForm
    template_name = 'apl/users_list.html'
    context_object_name = 'apl'


class ApplicationCreateView(CreateView):
    model = Application
    form_class = ApplicationForm
    template_name = 'apl/create.html'
    context_object_name = 'apl'
    success_url = reverse_lazy('apl_create')

    def form_valid(self, form):
        messages.success(self.request, 'Application successfully created.')
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('files')
        if form.is_valid():
            id = form.save().pk
            application = Application.objects.get(pk=id)
            if files:
                for f in files:
                    fl = Files(application=application, file=f)
                    fl.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

templates/apl/create.html
{% extends 'base.html' %}

{% block content %}

  <h1 class="text-center mt-5">Create Application</h1>
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <label for="title">Title</label>
      <input type="text" class="form-control" id="title" name="title" required>
    </div>
    <div class="form-group">
      <label for="text">Text</label>
      <textarea class="form-control" id="text" name="text" rows="3" required></textarea>
    </div>
    <div class="form-group">
      <label for="urgency">Urgency</label>
      <select class="form-control" id="urgency" name="urgency" required>
        <option value="не срочно">не срочно</option>
        <option value="срочно">срочно</option>
        <option value="очень срочно">очень срочно</option>
      </select>
    </div>
    <div class="form-group">
  <label for="files">Files:</label>
  <input type="file" class="form-control-file" name="files" multiple="multiple">
</div>
    <button type="submit" class="btn btn-light" style="background-color: #C591FF" >Submit</button>
    <a href="http://127.0.0.1:8000/" class="btn btn-light" aria-current="page" style="background-color: #764EED">All application</a>
  </form>
{% endblock %}

templates/apl/users_list.html
{% extends "base.html" %}
{% block content %}


<table class="table table-bordered">
  <thead style="background-color: #FFFFFF" >
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Urgency</th>
      <th scope="col">File</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody  style="background-color: #FFFFFF" >
    {% for application in apl %}
      <tr>
        <td>{{ application.title }}</td>
        <td>{{ application.urgency}}</td>
        <td>
          {% for file in application.files_set.all %}
            {{ file.file.name }}<br>
          {% endfor %}
        </td>
        <td>
          {% for file in application.files_set.all %}
            <a href="{{ file.file.url }}" class="btn-group-vertical"  download>Download</a><br>
          {% endfor %}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}


templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>Application</title>
</head>
<body style="background-color: #D3CFFF">
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>